#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SqliteDemo.Resource", IsApplication=true)]

namespace SqliteDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::SqliteDemo.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::SqliteDemo.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int add_btn_add = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int add_edit_age = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int add_edit_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int add_edit_sex = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int del_btn_del = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int del_edit_id = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int main_btn_add = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int main_btn_del = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int main_btn_que = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int que_text_res = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AddLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DeleteLayout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int QueryLayout = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int app_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
